### PR TITLE
Fix signet indexing 

### LINKED ISSUE #62: Fix signet indexing
tried running the example, everything works smothly on regtest but on signet i get an error results below :
signet
```
tx-indexer on  tip-to-depth is 📦 v0.1.0 via 🦀 v1.92.0-nightly took 14s 
❯ time cargo run --example indexer -- --datadir ~/.bitcoin/signet --depth 10
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/indexer --datadir /home/shehu/.bitcoin/signet --depth 10`
Indexing 11 blocks from tip (datadir: /home/shehu/.bitcoin/signet)
Error: failed to build indices: parse: unexpected eof at offset 3138913497 (len 50331648)
cargo run --example indexer -- --datadir ~/.bitcoin/signet --depth 10  3.99s user 0.15s system 100% cpu 4.140 total

tx-indexer on  tip-to-depth is 📦 v0.1.0 via 🦀 v1.92.0-nightly took 4s 
❯ time cargo run --example indexer -- --datadir ~/.bitcoin/signet --depth 10
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/indexer --datadir /home/shehu/.bitcoin/signet --depth 10`
Indexing 11 blocks from tip (datadir: /home/shehu/.bitcoin/signet)
Error: failed to build indices: parse: unexpected eof at offset 3138913497 (len 50331648)
cargo run --example indexer -- --datadir ~/.bitcoin/signet --depth 10  3.98s user 0.14s system 100% cpu 4.125 total
```

regtest 
```
tx-indexer on  tip-to-depth is 📦 v0.1.0 via 🦀 v1.92.0-nightly took 6s 
❯ time cargo run --example indexer -- --datadir ~/.bitcoin/regtest --depth 100           
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/examples/indexer --datadir /home/shehu/.bitcoin/regtest --depth 100`
Indexing 101 blocks from tip (datadir: /home/shehu/.bitcoin/regtest)
Indexed 112 transactions in 101 blocks (478.39ms)

--- RBF signaling analysis (2.88ms) ---
Transactions signaling RBF: 11/112 (9.8%)
cargo run --example indexer -- --datadir ~/.bitcoin/regtest --depth 100  0.51s user 0.09s system 96% cpu 0.618 total
```

_Originally posted by @Mshehu5 in https://github.com/payjoin/tx-indexer/pull/39#discussion_r3097266893_

### PR DESCRIPTION
**Pull request by Mshehu5**
closes: #62 
This PR fixes blk file parsing by using Bitcoin Core’s recorded logical file size (BlockFileInfo.size) instead of the raw filesystem length. That prevents the parser from reading into the preallocated tail of the active blk*.dat file, which can look like garbage after XOR decoding and cause unexpected EOF errors.

Reasoning for this approach are here  https://github.com/payjoin/tx-indexer/issues/62#issuecomment-4290059480

Message for reviwers:
After this fix indexing is working with results below, but if a better approach is available would appreciate suggestions

```
tx-indexer on  data_length [$!?] is 📦 v0.1.0 via 🦀 v1.92.0-nightly 
❯ time cargo run --example indexer -- --datadir ~/.bitcoin/signet --depth 1000
   Compiling tx-indexer-primitives v0.1.0 (/home/shehu/Documents/os/tx-indexer/src/crates/primitives)
   Compiling tx-indexer-fingerprints v0.1.0 (/home/shehu/Documents/os/tx-indexer/src/crates/fingerprints)
   Compiling tx-indexer-pipeline v0.1.0 (/home/shehu/Documents/os/tx-indexer/src/crates/pipeline)
   Compiling tx-indexer-heuristics v0.1.0 (/home/shehu/Documents/os/tx-indexer/src/crates/heuristics)
   Compiling bitcoin-transaction-indexer v0.1.0 (/home/shehu/Documents/os/tx-indexer)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.84s
     Running `target/debug/examples/indexer --datadir /home/shehu/.bitcoin/signet --depth 1000`
Indexing last 1001 blocks (depth: 1000) from /home/shehu/.bitcoin/signet
Indexed 90835 transactions in 1001 blocks (27.46s)

--- RBF signaling analysis (5.49s) ---
Transactions signaling RBF: 58863/90835 (64.8%)
cargo run --example indexer -- --datadir ~/.bitcoin/signet --depth 1000  31.64s user 4.81s system 107% cpu 33.976 total

tx-indexer on  data_length [$!?] is 📦 v0.1.0 via 🦀 v1.92.0-nightly took 34s 
❯ time cargo run --example indexer -- --datadir ~/.bitcoin/signet --depth 100 
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/indexer --datadir /home/shehu/.bitcoin/signet --depth 100`
Indexing last 101 blocks (depth: 100) from /home/shehu/.bitcoin/signet
Indexed 13253 transactions in 101 blocks (7.11s)

--- RBF signaling analysis (860.65ms) ---
Transactions signaling RBF: 7659/13253 (57.8%)
cargo run --example indexer -- --datadir ~/.bitcoin/signet --depth 100  7.68s user 0.68s system 102% cpu 8.137 total
```

### CODE REVIEW

File: src/crates/primitives/src/parser.rs [hunk 1]
```diff
@@ -75,8 +81,13 @@ impl Parser {
...
     ) -> Result<(), BlockFileError> {
         // Default: single file starting at height 0.
-        let default_hint = [(0u32, 0u32, u32::MAX)];
-        let hints: &[(u32, u32, u32)] = if self.file_hints.is_empty() {
+        let default_hint = [BlkFileHint {
+            file_no: 0,
+            height_first: 0,
+            height_last: u32::MAX,
+            data_len: None,
+        }];
```
Comment (arminsabouri) [inline src/crates/primitives/src/parser.rs]: Can we impl Default instead?

File: src/crates/primitives/src/parser.rs [hunk 2]
```diff
@@ -98,6 +111,22 @@ impl Parser {
 
             let file_id = BlockFileId(file_no);
             let bytes = self.store.read_file(file_no).map_err(BlockFileError::Io)?;
+            let used_len = match hint.data_len {
+                Some(data_len) => {
+                    let used_len = data_len as usize;
```
Comment (arminsabouri) [inline src/crates/primitives/src/parser.rs]: Should this type just be usize on the FileHints struct?

```suggestion
                    let used_len = data_len;
```

File: src/crates/primitives/src/parser.rs [hunk 3]
```diff
@@ -24,16 +24,24 @@ const BLOCK_START_LEN: usize = 8;
 
 // TODO: provide option to memory map the block files
 
+#[derive(Debug, Clone, Copy, PartialEq, Eq)]
+pub struct BlkFileHint {
+    pub file_no: u32,
+    pub height_first: u32,
+    pub height_last: u32,
+    pub data_len: Option<u32>,
```
Comment (arminsabouri) [inline src/crates/primitives/src/parser.rs]: Why is it optional?

File: src/crates/primitives/src/unified/mod.rs [hunk 4]
```diff
@@ -192,10 +192,10 @@ pub struct DenseBuildSpec {
     pub range: Range<u64>,
     pub paths: dense::IndexPaths,
     pub spk_db: SledScriptPubkeyDb,
-    /// Blk file layout hints: `(file_no, height_first, height_last)`, sorted by `file_no`.
+    /// Blk file layout hints derived from Bitcoin Core's block index.
```
Comment (arminsabouri) [inline src/crates/primitives/src/unified/mod.rs]: This seems like a regression. I would revert and just reference the new struct `BlkFileHints`

File: src/crates/primitives/src/parser.rs (hunk 3 above)
Comment (arminsabouri) [inline src/crates/primitives/src/parser.rs]: A rustdoc for this would be useful. esp. since later in this PR its re-assigned a var called `used_len`?

**Review by arminsabouri — CHANGES_REQUESTED** [review]

**Review by bc1cindy — COMMENTED** [review]
good catch!

could we add a test that builds a synthetic blk file with garbage past `data_len` and asserts the parse stops cleanly? 

that would pin down the signet regression against future changes

**Comment by arminsabouri** [comment]
> good catch!
> 
> could we add a test that builds a synthetic blk file with garbage past `data_len` and asserts the parse stops cleanly?
> 
> that would pin down the signet regression against future changes

Yes to adding a test for this. It can live with the other blk file test fixtures. I am not sure how to get actually generate this fixture.

**Comment by bc1cindy** [comment]
> I am not sure how to get actually generate this fixture.

maybe using one that already exists and appending zeros?

**Comment by arminsabouri** [comment]
> > I am not sure how to get actually generate this fixture.
> 
> maybe using one that already exists and appending zeros?

I don't think that will work. You would also need to update the leveldb index

File: src/crates/primitives/src/parser.rs (hunk 3 above)
Comment (Mshehu5) [reply src/crates/primitives/src/parser.rs]: It’s optional because not every parser path has a known logical blk file size. its a fallaback inase we get NONE. None means “fall back to the full file length”

**Comment by arminsabouri** [comment]
Sorry @Mshehu5 with #61 merged there are some conflicts

**Comment by Mshehu5** [comment]
> Sorry @Mshehu5 with #61 merged there are some conflicts

Thanks for the heads up. Merged conflicts addressed good to go

File: src/crates/primitives/src/parser.rs (hunk 3 above)
Comment (arminsabouri) [reply src/crates/primitives/src/parser.rs]: Do you mean not every blk file has a logical size? It seems like its always set to Some() in method that creates the hints?

Comment (Mshehu5) [reply src/crates/primitives/src/parser.rs]: yes those are always Some(info.size). The Option is only for the parser fallback path when no hints are provided where we still allow BlkFileHint::default() / empty hints and do not know the logical size up front.

check parser.rs line 47

**Review by arminsabouri — APPROVED** [review]
cACK 2edce7dfdce1de414a9462b48b2999cd747be584
